version: 2.2-{build}

branches:
  only:
  - master

skip_tags: true

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2204
  - APPVEYOR_BUILD_WORKER_IMAGE: macos-sonoma

install:
- sh: |
    if [ "$CI_LINUX" = "true" ]; then
        sudo apt-get update &&
        sudo apt-get -y install gcc-multilib
    fi

build_script:
- cmd: |
    cd build\windows\ && ^
    build.bat ^
    cd ..\..
- sh: |
    if [ "$CI_LINUX" = "true" ]; then
        cd build/linux/ &&
        ./build.sh &&
        cd ../..
    else
        cd build/macos/ &&
        ./build.sh &&
        cd ../..
    fi

test_script:
- cmd: |
    cd .\test\Pkcs11LoggerTests\ && ^
    nuget install Appveyor.TestLogger && ^
    dotnet build && ^
    cd ..\..
    dotnet vstest .\test\Pkcs11LoggerTests\bin\Debug\net60\Pkcs11LoggerTests.dll --TestAdapterPath:. --logger:Appveyor
- sh: |
    cd ./test/Pkcs11LoggerTests/ &&
    nuget install -Source https://api.nuget.org/v3/index.json Appveyor.TestLogger &&
    dotnet build && 
    cd ../..
    dotnet test --test-adapter-path:. --logger:Appveyor ./test/Pkcs11LoggerTests/

artifacts:
- path: build/windows/pkcs11-logger-*.dll
- path: build/linux/pkcs11-logger-*.so
- path: build/macos/pkcs11-logger.dylib
