version: 2.2-{build}

branches:
  only:
  - master

skip_tags: true

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022

build_script:
- cmd: cd build\windows\ && build.bat

test_script:
- cmd: cd .\test\Pkcs11LoggerTests\ && nuget install Appveyor.TestLogger && dotnet build && cd ..\..
- cmd: dotnet vstest .\test\Pkcs11LoggerTests\bin\Debug\net60\Pkcs11LoggerTests.dll --TestAdapterPath:. --logger:Appveyor

artifacts:
- path: build/windows/
  name: pkcs11-logger-