CC= gcc
CFLAGS= -g -Wall -O2 -I.

all: lock.o log.o pkcs11-logger.o translate.o
	$(CC) -shared -o pkcs11-logger.dll lock.o log.o pkcs11-logger.o translate.o

lock.o: lock.c pkcs11-logger.h
	$(CC) $(CFLAGS) -c lock.c

log.o: log.c pkcs11-logger.h
	$(CC) $(CFLAGS) -c log.c

pkcs11-logger.o: pkcs11-logger.c pkcs11-logger.h
	$(CC) $(CFLAGS) -c pkcs11-logger.c

translate.o: translate.c pkcs11-logger.h
	$(CC) $(CFLAGS) -c translate.c

clean:
	-rm -f *.o

distclean: clean
	-rm -f *.dll
